ci(deps): bump the all group across 1 directory with 2 updates (#132)
Bumps the all group with 2 updates in the /.github/workflows directory:
[marocchino/sticky-pull-request-comment](https://github.com/marocchino/sticky-pull-request-comment)
and [arduino/setup-task](https://github.com/arduino/setup-task).

Updates `marocchino/sticky-pull-request-comment` from 3.0.4 to 3.0.5
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/marocchino/sticky-pull-request-comment/releases">marocchino/sticky-pull-request-comment's
releases</a>.</em></p>
<blockquote>
<h2>v3.0.5</h2>
<h2>What's Changed</h2>
<ul>
<li>build(deps-dev): Bump rollup from 4.60.1 to 4.60.2 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1687">marocchino/sticky-pull-request-comment#1687</a></li>
<li>build(deps-dev): Bump typescript from 6.0.2 to 6.0.3 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1686">marocchino/sticky-pull-request-comment#1686</a></li>
<li>build(deps-dev): Bump <code>@​biomejs/biome</code> from 2.4.11 to
2.4.12 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1685">marocchino/sticky-pull-request-comment#1685</a></li>
<li>build(deps-dev): Bump vitest from 4.1.4 to 4.1.5 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1688">marocchino/sticky-pull-request-comment#1688</a></li>
<li>build(deps): Bump <code>@​actions/glob</code> from 0.6.1 to 0.7.0 by
<a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1689">marocchino/sticky-pull-request-comment#1689</a></li>
<li>build(deps): Bump <code>@​actions/core</code> from 3.0.0 to 3.0.1 by
<a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1690">marocchino/sticky-pull-request-comment#1690</a></li>
<li>build(deps): Bump <code>@​actions/github</code> from 9.1.0 to 9.1.1
by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1691">marocchino/sticky-pull-request-comment#1691</a></li>
<li>build(deps-dev): Bump <code>@​biomejs/biome</code> from 2.4.12 to
2.4.13 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1693">marocchino/sticky-pull-request-comment#1693</a></li>
<li>feat: embed file content in message template via
<code>{{{content}}}</code> placeholder by <a
href="https://github.com/marocchino"><code>@​marocchino</code></a> with
<a href="https://github.com/Copilot"><code>@​Copilot</code></a> in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1665">marocchino/sticky-pull-request-comment#1665</a></li>
<li>build(deps-dev): Bump <code>@​biomejs/biome</code> from 2.4.13 to
2.4.14 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1694">marocchino/sticky-pull-request-comment#1694</a></li>
<li>build(deps-dev): Bump rollup from 4.60.2 to 4.60.3 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1695">marocchino/sticky-pull-request-comment#1695</a></li>
<li>build(deps-dev): Bump <code>@​types/node</code> from 25.6.0 to
25.6.2 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1698">marocchino/sticky-pull-request-comment#1698</a></li>
<li>build(deps-dev): Bump <code>@​types/node</code> from 25.6.2 to
25.7.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1700">marocchino/sticky-pull-request-comment#1700</a></li>
<li>build(deps-dev): Bump vitest from 4.1.5 to 4.1.6 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1701">marocchino/sticky-pull-request-comment#1701</a></li>
<li>build(deps-dev): Bump <code>@​types/node</code> from 25.7.0 to
25.8.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1703">marocchino/sticky-pull-request-comment#1703</a></li>
<li>build(deps-dev): Bump rollup from 4.60.3 to 4.60.4 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1704">marocchino/sticky-pull-request-comment#1704</a></li>
<li>build(deps-dev): Bump <code>@​types/node</code> from 25.8.0 to
25.9.1 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1707">marocchino/sticky-pull-request-comment#1707</a></li>
<li>build(deps-dev): Bump vitest from 4.1.6 to 4.1.7 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1708">marocchino/sticky-pull-request-comment#1708</a></li>
<li>build(deps): Bump brace-expansion from 5.0.5 to 5.0.6 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1705">marocchino/sticky-pull-request-comment#1705</a></li>
<li>build(deps): Bump undici from 6.24.0 to 6.27.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1725">marocchino/sticky-pull-request-comment#1725</a></li>
<li>build(deps-dev): Bump rollup from 4.60.4 to 4.62.2 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1722">marocchino/sticky-pull-request-comment#1722</a></li>
<li>build(deps): Bump actions/checkout from 6 to 7 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1721">marocchino/sticky-pull-request-comment#1721</a></li>
<li>build(deps-dev): Bump vite from 8.0.13 to 8.0.16 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1720">marocchino/sticky-pull-request-comment#1720</a></li>
<li>build(deps-dev): Bump vitest from 4.1.7 to 4.1.9 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1719">marocchino/sticky-pull-request-comment#1719</a></li>
<li>build(deps-dev): Bump <code>@​types/node</code> from 25.9.1 to
26.1.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1731">marocchino/sticky-pull-request-comment#1731</a></li>
<li>build(deps-dev): Bump <code>@​rollup/plugin-commonjs</code> from
29.0.2 to 29.0.3 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1710">marocchino/sticky-pull-request-comment#1710</a></li>
<li>build(deps-dev): Bump js-yaml from 4.1.1 to 5.2.1 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1732">marocchino/sticky-pull-request-comment#1732</a></li>
<li>build(deps-dev): Bump <code>@​biomejs/biome</code> from 2.4.14 to
2.5.2 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/pull/1730">marocchino/sticky-pull-request-comment#1730</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/marocchino/sticky-pull-request-comment/compare/v3.0.4...v3.0.5">https://github.com/marocchino/sticky-pull-request-comment/compare/v3.0.4...v3.0.5</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/marocchino/sticky-pull-request-comment/commit/5770ad5eb8f42dd2c4f34da00c94c5381e49af88"><code>5770ad5</code></a>
📦️ Build</li>
<li><a
href="https://github.com/marocchino/sticky-pull-request-comment/commit/2c190609760f3bf7b8298e5e88612e77a6d49ecc"><code>2c19060</code></a>
build(deps-dev): Bump <code>@​biomejs/biome</code> from 2.4.14 to 2.5.2
(<a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/issues/1730">#1730</a>)</li>
<li><a
href="https://github.com/marocchino/sticky-pull-request-comment/commit/3d24e5ae13e5cb81ea2bc10645b7d737cf11902f"><code>3d24e5a</code></a>
build(deps-dev): Bump js-yaml from 4.1.1 to 5.2.1 (<a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/issues/1732">#1732</a>)</li>
<li><a
href="https://github.com/marocchino/sticky-pull-request-comment/commit/36048210fda2e47994091215455a64526baf9829"><code>3604821</code></a>
build(deps-dev): Bump <code>@​rollup/plugin-commonjs</code> from 29.0.2
to 29.0.3 (<a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/issues/1710">#1710</a>)</li>
<li><a
href="https://github.com/marocchino/sticky-pull-request-comment/commit/a4d9c0f61c8b826000881e93dcf8d3c3de9e6d82"><code>a4d9c0f</code></a>
build(deps-dev): Bump <code>@​types/node</code> from 25.9.1 to 26.1.0
(<a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/issues/1731">#1731</a>)</li>
<li><a
href="https://github.com/marocchino/sticky-pull-request-comment/commit/ae65a58300ab21f85000f649966645a4f8b98c7e"><code>ae65a58</code></a>
build(deps-dev): Bump vitest from 4.1.7 to 4.1.9 (<a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/issues/1719">#1719</a>)</li>
<li><a
href="https://github.com/marocchino/sticky-pull-request-comment/commit/86803217fddacb4de85c3e9724a5562badaa8c8e"><code>8680321</code></a>
build(deps-dev): Bump vite from 8.0.13 to 8.0.16 (<a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/issues/1720">#1720</a>)</li>
<li><a
href="https://github.com/marocchino/sticky-pull-request-comment/commit/5d402391401fd084c1a074525b8c1f306989428f"><code>5d40239</code></a>
build(deps): Bump actions/checkout from 6 to 7 (<a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/issues/1721">#1721</a>)</li>
<li><a
href="https://github.com/marocchino/sticky-pull-request-comment/commit/39ab01d7848066124dd3483f4186a8ec4b5f8f3d"><code>39ab01d</code></a>
build(deps-dev): Bump rollup from 4.60.4 to 4.62.2 (<a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/issues/1722">#1722</a>)</li>
<li><a
href="https://github.com/marocchino/sticky-pull-request-comment/commit/b2660f1f0ba080a208cdb3834816c6012377e8b6"><code>b2660f1</code></a>
build(deps): Bump undici from 6.24.0 to 6.27.0 (<a
href="https://redirect.github.com/marocchino/sticky-pull-request-comment/issues/1725">#1725</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/marocchino/sticky-pull-request-comment/compare/0ea0beb66eb9baf113663a64ec522f60e49231c0...5770ad5eb8f42dd2c4f34da00c94c5381e49af88">compare
view</a></li>
</ul>
</details>
<br />

Updates `arduino/setup-task` from 2.0.0 to 3.0.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/arduino/setup-task/releases">arduino/setup-task's
releases</a>.</em></p>
<blockquote>
<h2>3.0.0</h2>
<h2>Migration Guide</h2>
<p>The version of the <a
href="https://nodejs.org/en/about"><strong>Node.js</strong></a> runtime
used to execute the action has been updated from 20 to 24. This could be
a breaking change for certain GitHub Actions workflows.</p>
<p>If a workflow with dependency on the
<strong>arduino/setup-task</strong> action uses only <a
href="https://docs.github.com/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners">GitHub-hosted
GitHub Actions runners</a>, no changes are required.</p>
<p>If the workflow uses a <a
href="https://docs.github.com/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners">self-hosted
runner</a>, the workflow run might fail after updating
<strong>arduino/setup-task</strong>:</p>
<pre lang="text"><code>Error: System.ArgumentOutOfRangeException:
Specified argument was out of the range of valid values. (Parameter
''using: node24' is not supported, use 'docker', 'node16' or 'node20'
instead.')
at
GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext
executionContext, TemplateContext templateContext, TemplateToken
inputsToken, String fileRelativePath, MappingToken outputs)
at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext
executionContext, String manifestFile)
Error: Fail to load arduino/setup-task/v3/action.yml
</code></pre>
<p>This means an older runner version that does not provide Node.js 24.x
is installed on the runner machine. In this case, the runner must be
updated to a modern version with Node.js 24.x support prior to updating
the <strong>arduino/setup-task</strong> action in the affected
workflow.</p>
<h2>Changelog</h2>
<h3>Breaking</h3>
<ul>
<li>Update Node.js runtime for action from 20 to 24 (<a
href="https://redirect.github.com/arduino/setup-task/issues/1408">#1408</a>)</li>
</ul>
<h3>Enhancement</h3>
<ul>
<li>Convert project to ECMAScript module format (<a
href="https://redirect.github.com/arduino/setup-task/issues/1410">#1410</a>)</li>
<li><a
href="https://github.com/arduino/setup-task/pulls?q=merged%3A2024-02-07..2026-06-30+author%3Aapp%2Fdependabot">Various
dependency updates</a></li>
</ul>
<h2>Full Changeset</h2>
<p><a
href="https://github.com/arduino/setup-task/compare/v2.0.0...v3.0.0">https://github.com/arduino/setup-task/compare/v2.0.0...v3.0.0</a></p>
<h2>Contributors</h2>
<ul>
<li><a href="https://github.com/tbjers"><code>@​tbjers</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/arduino/setup-task/commit/c0bc642852239c2689f73f4ea6459c29405f3c52"><code>c0bc642</code></a>
Merge pull request <a
href="https://redirect.github.com/arduino/setup-task/issues/1412">#1412</a>
from arduino/dependabot/npm_and_yarn/prettier-3.9.4</li>
<li><a
href="https://github.com/arduino/setup-task/commit/c07d23ea793b3a5079f5da132345e36183e80c16"><code>c07d23e</code></a>
build(deps-dev): bump prettier from 3.9.3 to 3.9.4</li>
<li><a
href="https://github.com/arduino/setup-task/commit/f08c616dcb5ae62ea47eee8cc9911c59ce13cd90"><code>f08c616</code></a>
Merge pull request <a
href="https://redirect.github.com/arduino/setup-task/issues/1413">#1413</a>
from arduino/dependabot/npm_and_yarn/vercel/ncc-0.44.1</li>
<li><a
href="https://github.com/arduino/setup-task/commit/92587414bbffd5f297a4d1f30510c4f447228aa3"><code>9258741</code></a>
build(deps-dev): bump <code>@​vercel/ncc</code> from 0.44.0 to
0.44.1</li>
<li><a
href="https://github.com/arduino/setup-task/commit/5da2ac77a85b357a4d3e163ae651fd180f365535"><code>5da2ac7</code></a>
Merge pull request <a
href="https://redirect.github.com/arduino/setup-task/issues/1341">#1341</a>
from arduino/dependabot/npm_and_yarn/actions/tool-ca...</li>
<li><a
href="https://github.com/arduino/setup-task/commit/939b4bbabffe5d1effc3740af4eb8be032d74341"><code>939b4bb</code></a>
Update dependency license metadata cache for
<code>@actions/tool-cache</code> bump</li>
<li><a
href="https://github.com/arduino/setup-task/commit/8ee93edf455c7aece15318ba3664b851d61fc9ee"><code>8ee93ed</code></a>
Repackage action following <code>@actions/tool-cache</code> bump</li>
<li><a
href="https://github.com/arduino/setup-task/commit/d179139bcb35cbf33f7538a4e9e8ad47f4a2ece0"><code>d179139</code></a>
build(deps): bump <code>@​actions/tool-cache</code> from 3.0.1 to
4.0.0</li>
<li><a
href="https://github.com/arduino/setup-task/commit/fdf1a08b64f84aa451e0513053f5fa8977075e2e"><code>fdf1a08</code></a>
Merge pull request <a
href="https://redirect.github.com/arduino/setup-task/issues/1340">#1340</a>
from arduino/dependabot/npm_and_yarn/actions/io-3.0.2</li>
<li><a
href="https://github.com/arduino/setup-task/commit/b3c627a805d5433989ce4dee31a6af95f5275055"><code>b3c627a</code></a>
Repackage action following <code>@actions/io</code> bump</li>
<li>Additional commits viewable in <a
href="https://github.com/arduino/setup-task/compare/b91d5d2c96a56797b48ac1e0e89220bf64044611...c0bc642852239c2689f73f4ea6459c29405f3c52">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>